name: LaTeX compilation

on: [ push, check_run ]
jobs:
  build_latex:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Curriculum (es)
        uses: dante-ev/latex-action@master
        with:
          root_file: curriculum.tex
      - name: Compile Curriculum (en)
        uses: dante-ev/latex-action@master
        with:
          root_file: curriculum_en.tex
